#PRIVILEGE DEFINE
ACCESS_BACKEND = 1
PROBLEM_VISIBLE = 2
ADD_PROBLEM = 4
ADD_MY_CONTEST = 8
ALL_SEE = 16


#PRIVILEGE
ADMIN = ACCESS_BACKEND + ADD_PROBLEM + PROBLEM_VISIBLE + ADD_MY_CONTEST + ALL_SEE 
ADD_PRO = ACCESS_BACKEND + ADD_PROBLEM   #5 
ADD_PRO_AND_PRO_VIS = ACCESS_BACKEND + ADD_PROBLEM + PROBLEM_VISIBLE #7
ADD_CON_AND_PRO = ACCESS_BACKEND + ADD_PROBLEM + ADD_MY_CONTEST #13
ADD_CON_AND_PRO_AND_VIS = ACCESS_BACKEND + PROBLEM_VISIBLE + ADD_PROBLEM + ADD_MY_CONTEST

PAGE_COUNT = 10
