#PRIVILEGE DEFINE
ACCESS_BACKEND = 1
_PROBLEM_VISIBLE = 2
_ADD_PROBLEM = 4
_ADD_MY_CONTEST = 8
_ALL_SEE = 16


#PRIVILEGE
ADMIN = ACCESS_BACKEND + _ADD_PROBLEM + _PROBLEM_VISIBLE + _ADD_MY_CONTEST + _ALL_SEE 
ADD_PRO = ACCESS_BACKEND + _ADD_PROBLEM   #5 
ADD_PRO_AND_PRO_VIS = ACCESS_BACKEND + _ADD_PROBLEM + _PROBLEM_VISIBLE #7
ADD_CON_AND_PRO = ACCESS_BACKEND + _ADD_PROBLEM + _ADD_MY_CONTEST #13
ADD_CON_AND_PRO_AND_VIS = ACCESS_BACKEND + _PROBLEM_VISIBLE + _ADD_PROBLEM + _ADD_MY_CONTEST
